[workspace]
members = [
  "ntex-cors",
  "ntex-files",
  "ntex-identity",
  "ntex-multipart",
  "ntex-session",
]
resolver = "3"

[workspace.package]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.85"
