[package]
name = "ntex-multipart"
version = "0.4.0-b.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Multipart support for ntex web framework."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "ntex"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-multipart/"
license = "MIT"
edition = "2018"

[lib]
name = "ntex_multipart"
path = "src/lib.rs"

[dependencies]
ntex = "1.0.0-b.1"
derive_more = "0.99"
httparse = "1.3"
futures = "0.3"
log = "0.4"
mime = "0.3"
twoway = "0.2"

[dev-dependencies]
ntex = { version = "1.0.0-b.1", features=["tokio"] }
