[package]
name = "ntex-multipart"
version = "0.1.0"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Multipart support for ntex web framework."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "ntex"]
homepage = "https://ntex.rs"
repository = "https://github.com/ntex-rs/ntex-extras.git"
documentation = "https://docs.rs/ntex-multipart/"
license = "MIT"
edition = "2018"

[lib]
name = "ntex_multipart"
path = "src/lib.rs"

[dependencies]
ntex = "0.2.0-b.14"
bytes = "0.5.6"
derive_more = "0.99.5"
httparse = "1.3"
futures = "0.3.12"
log = "0.4"
mime = "0.3"
twoway = "0.2"
